Second
FatykovKirill/GenerationPassword pull request #1
Opened 2022-11-07 15:11 UTC by FatykovKirill

2022-11-07 15:37 UTC, andrey-kudinov requested changes
Хорошая работа 👍
Посмотри пж несколько комментариев
Можно будет обсудить их в тг

2022-11-07 15:37 UTC, andrey-kudinov commented on css/style.css
> +
Можно на body повесить следующие свойства и это центрирует контент
```
display: grid;
place-items: center;
min-height: 100vh;
```

2022-11-07 15:37 UTC, andrey-kudinov commented on js/main.js
> +    if (length > 100) {
Можно ещё на НЕ цифры и отрицательные значения сделать проверки

2022-11-07 15:37 UTC, andrey-kudinov commented on js/main.js
> +    if (length > 100) {
Прям в этом же условии

2022-11-07 15:37 UTC, andrey-kudinov commented on js/main.js
> +    if (hasSymbols) {
Почему здесь дважды один и тот же код код, здесь и ниже в цикле?

2022-11-07 15:37 UTC, andrey-kudinov commented on js/main.js
> +// function checkInput(obj) {
Лучше удалить комментарий если он больше не нужен

2022-11-07 15:37 UTC, andrey-kudinov commented on js/main.js
> +    const specialSymbols = '!"#$%&\'()*+,-./:;<=>?@[\]^_`{|}~';
Эти значения можно вынести выше и выводить в описании в HTML на 26 строчке, чтобы не было рассинхрона
Можно для красоты сократить количество спец символов

2022-11-08 15:30 UTC, FatykovKirill commented
merge

2022-11-08 15:31 UTC, merged